name: educatly_task
description: "A new Flutter project."


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

  flutter_screenutil: ^5.9.3
  animate_do: ^3.3.4

  flutter_bloc: ^8.1.6
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  build_runner: ^2.4.13

  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/welcome.png
    - assets/images/login.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
